logging:
  level:
    reactor.netty: trace
    io.netty: trace
    
---
spring:  profiles:  - local
  
server:
  port: 8443
  http2:
    enabled: true    ssl: 
    key-store: classpath:local.p12
    key-store-type: PKCS12
    key-store-password: abcd1234
    key-alias: baeldung

---
spring:  profiles:  - k8s

server:  port: 8080
  forward-headers-strategy: native