server:
  port: 8443
  http2:
    enabled: true

logging:
  level:
    reactor.netty: debug
    io.netty: debug
    
---
spring:  profiles:  - local
  
server:  ssl: 
    key-store: classpath:local.p12
    key-store-type: PKCS12
    key-store-password: abcd1234
    key-alias: baeldung

---
spring:  profiles:  - k8s